# Generated by Django 4.2.7 on 2023-11-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_book_rent_delete_review'),
    ]

    operations = [
    ]
