# Generated by Django 4.2.7 on 2023-11-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20231124_1958'),
    ]

    operations = [
    ]
